//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaVentas.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

     [Table("detalle_venta")]
    public partial class detalle_venta
    {
         [Key]
        public int iddetalle_venta { get; set; }
        public int idventa { get; set; }
        public int idarticulo { get; set; }
        public int cantidad { get; set; }
        public decimal precio_venta { get; set; }
        public decimal descuento { get; set; }
    
        public virtual articulo articulo { get; set; }
        public virtual venta venta { get; set; }
    }
}
